version: "3.5"

services:
  dumper:
    container_name: dumper
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backups:/var/backups
      - ./logs:/logs
    env_file: .env
    restart: on-failure
    tty: true
